# Generated by Django 5.0.3 on 2024-03-14 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1023)),
                ('image', models.ImageField(upload_to='question/question_image')),
                ('choice_1', models.CharField(max_length=511)),
                ('choice_2', models.CharField(max_length=511)),
                ('choice_3', models.CharField(max_length=511)),
                ('choice_4', models.CharField(max_length=511)),
                ('answer', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=1)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('question_maker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
